apiVersion: v1
kind: Secret
metadata:
  name: obs-secrets
  namespace: {{ .Values.namespace }}
type: Opaque
stringData:
  DATABASE_URL:      {{ .Values.db.url | quote }}
  POSTGRES_PASSWORD: {{ .Values.db.password | quote }}
