apiVersion: v1
kind: Service
metadata:
  name: query-api
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: query-api
  ports:
    - name: http
      port: 4000
      targetPort: 4000
    - name: metrics
      port: 4001
      targetPort: 4001